spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: fisnik
    password: Password!23
    jpa:
      hibernate:
        ddl-auto: validate
        database-platform: org.hibernate.dialect.MySQL8Dialect
        database: mysql
        show-sql: true